### ISSUE TITLE
train_fm.py: IndexError: list index out of range

### ISSUE THREAD

**Issue by adegirmenci** [Atcold/pytorch-PPUU#21]
```
python train_fm.py -model_dir ~/PPUU-models --model fwd-cnn-vae-fp

[loading data shard: traffic-data/state-action-cost/data_i80_v0/trajectories-0400-0415/all_data.pth]
[loading data shard: traffic-data/state-action-cost/data_i80_v0/trajectories-0500-0515/all_data.pth]
[loading data shard: traffic-data/state-action-cost/data_i80_v0/trajectories-0515-0530/all_data.pth]
Number of episodes: 5596
[loading data splits: traffic-data/state-action-cost/data_i80_v0/splits.pth]
[loading data stats: traffic-data/state-action-cost/data_i80_v0/data_stats.pth]
[loading car sizes: traffic-data/state-action-cost/data_i80_v0/car_sizes.pth]
[will save model as: ~/PPUU-models/model=fwd-cnn-vae-fp-layers=3-bsize=8-ncond=20-npred=20-lrt=0.0001-nfeature=256-dropout=0.0-nz=32-beta=0.0-zdropout=0.0-gclip=5.0-warmstart=0-seed=1]
[training]
Traceback (most recent call last):
  File "train_fm.py", line 203, in <module>
    train_losses = train(opt.epoch_size, opt.npred)
  File "train_fm.py", line 148, in train
    inputs, actions, targets, _, _ = dataloader.get_batch_fm('train', npred)
  File "~/pytorch-PPUU/dataloader.py", line 175, in get_batch_fm
    car_id = int(re.findall('car(\d+).pkl', splits[5])[0])
IndexError: list index out of range
```

**Comment by mbhenaff** [comment]
This is fixed now.

**Comment by Atcold** [comment]
Thanks @mbhenaff!
